# Generated by Django 4.2.7 on 2025-06-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-importance', 'due_date', '-created_at'], 'verbose_name': 'タスク', 'verbose_name_plural': 'タスク'},
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='期限'),
        ),
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '重要')], default='medium', max_length=10, verbose_name='重要度'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=10, verbose_name='優先度'),
        ),
    ]
