# Generated by Django 4.2.7 on 2025-06-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_due_date_task_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='想定される作業時間を時間単位で入力', max_digits=5, null=True, verbose_name='想定作業時間（時間）'),
        ),
    ]
