# Generated by Django 4.2.7 on 2025-06-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_estimated_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-urgency', '-importance', 'due_date', '-created_at'], 'verbose_name': 'タスク', 'verbose_name_plural': 'タスク'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='緊急度'),
        ),
    ]
