# Generated by Django 4.2.7 on 2025-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_estimated_hours_alter_task_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_all_day',
            field=models.BooleanField(default=False, verbose_name='終日'),
        ),
    ]
