# Generated by Django 4.2.7 on 2025-06-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_is_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('important', '重要'), ('not_important', '重要ではない')], default='not_important', max_length=15, verbose_name='重要度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('urgent', '緊急'), ('not_urgent', '緊急ではない')], default='not_urgent', max_length=15, verbose_name='緊急度'),
        ),
    ]
